import zipfile
import os
from core.logger import get_logger

logger = get_logger(__name__)

def write_narrative_report(
    profile_text: str,
    explanation: str,
    output_path: str
) -> str:
    """
    Write a human-readable narrative report explaining
    what problems were found and what decisions were made.
    Returns the path to the written report file.
    """

    logger.info(f"Writing narrative report to {output_path}")
    report = """
===========================================
    AUTONOMOUS DATA ENGINEERING REPORT
===========================================

    DATASET PROFILE (BEFORE PROCESSING):
    ------------------------------------
    {profile_text}

    CLEANING & PREPROCESSING DECISIONS MADE:
    ------------------------------------
    {explanation}

============================================
        GENERATED BY AI AGENT
============================================
    """

    report = report.format(profile_text=profile_text, explanation=explanation)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report)
    return output_path
    

def bundle_outputs(
    csv_path: str,
    script_path: str,
    report_path: str,
    zip_path: str
) -> str:
    """
    Bundle all 3 output files into a single downloadable .zip.
    Returns the path to the zip file.
    """
    with zipfile.ZipFile(zip_path, "w") as zipf:
        zipf.write(csv_path, arcname="processed_data.csv")
        zipf.write(script_path, arcname="processing_script.py")
        zipf.write(report_path, arcname="report.txt")
    return zip_path